# Plugin affichant les entités Home Assistant.
#
# Utilise l’API REST de Home Assistant pour récupérer les classes et valeurs des entités.
---
name: 'Home Assistant Sensors'

custom_fields:
  - name: HomeAssistant URL
    keyname: url
    field_type: url
    description: Your HomeAssistant server URL.
  - name: HomeAssistant Token
    keyname: token
    field_type: string
    description: A token linked to a User with `GET /api/states/` permission.
  - name: Entities
    keyname: entities_ids
    field_type: multi_string
    description: List of entity to monitor.

strategy: polling
polling_url: |
  {% assign ids = entities_ids | split: "," %}{% for id in ids %}{{ url }}/api/states/{{ id }}
  {% endfor %}
polling_verb: get
polling_headers: "Authorization=Bearer {{ token }}"

no_screen_padding: 'no'
dark_mode: 'no'
static_data: '{}'
refresh_interval: 60
